---
- name: Install apache2 package
  ansible.builtin.apt:
    name: apache2
    state: present
- name: Ensure apache2 is running
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
- name: Create a sample index.html file
  ansible.builtin.copy:
    dest: /var/www/html/index.html
    content: "<html><body><h1>Welcome to the Apache Server!</h1></body></html>"
    mode: '0644'
