---
- name: Updating Webpage content using handlers & 'notify' and testing 'when'
  hosts: all
  become: true
  tasks:
    - name: Updating the index.html file
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "<html><body><h1>Welcome to the Updated Apache Server! @ V3</h1></body></html>"
        mode: '0644'
      when: ansible_facts['distribution'] == 'Ubuntu'
      notify: Restart apache2
  handlers:
    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
      when: ansible_facts['os_family'] == 'RedHat'
